logging:
  config: ./src/main/resources/logback-spring.xml
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/Restaurant?autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: Sotrisu_175
    testWhileIdle: true
    validationQuery: SELECT 1  
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
application:
  restaurant-opening-date: '2019-03'
  logs:
    directory: ./src/main/resources